language: node_js

node_js:
  - '6'

before_install:
  - rvm install 2.3.3
  - rvm use 2.3.3 --fuzzy
  - export GEMDIR=$(rvm gemdir)

before_script:
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - gem install bundler
  - bundle install
  - chmod +x ./travis.sh

script: "./travis.sh"

branches:
  only:
    - master

env:
  global:
    - secure: jHquMJQJM9MGpO78ToAUSvVcP/htSzEsGNNLPZmac4ROagyM4qtbp10EcmUnLJquW6Hzw/O3YSAZEVx+prYR0V5Fts6wkXsyytnZt2jym0S7yzZTEaYqOtrTyLDAlMD9PDrVoOoyCh+HmykkDlwzkicsIxE1W9pppM9RNw3oVVVhtFF3Suy7w4FZJkVKx5BNo1+ng8IOPBVYgA3JEJVB8qRe6VKQHQF+Pu6oU5icrxZ9B7yPZxlji7VMix1EX5vCa4AIUkNWJW/u2SWtSemAKBjBJXar4VsXky4mNbcIwZe4W9QGCgTm9zLfBjuvgAS7OyPpMqHqrt1BFGsx2Kz0K0Vt1zrzQTriQuhEHPbD2tnGsVX38tyq73eLrn4YNW9MBqX683zxcJrtc/wMu6uRY8weZ8QaUKs84m9TGQUIf2bmO7+xMIFf5KZ9Sa3FUbB/t3i9FXO5w7DyrvChvICXNlCqikoUNWVz75hjE9Knu/sHQT92BG8eAhZaZUDOt3WZdfVmGGBfRCNapUWF+2Q+d9M/9tQr2NWO2ByPtG4xgpiDAcSjWn9gq/WB22EcovXNml7oiJntxJIU2/ICQXVMN/hJs6XGXWx/CLhY3AHjgmz0upj9cwRt8Dwy1O0wZusKDuaDAYptU7sE5mnx6YeGPsusyKbtd2YvdvqSklxA+oI=
    - JEKYLL_ENV=production
    - JEKYLL_LOG_LEVEL=debug
    - GH_REF=github.com/ftp-sync/ftp-sync.github.io.git
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false