language: node_js
node_js: 11

env:
  global:
    - JEKYLL_ENV=production
    - JEKYLL_LOG_LEVEL=info
    - GH_REF=github.com/ftpgrab/ftpgrab.github.io.git
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - secure: jHquMJQJM9MGpO78ToAUSvVcP/htSzEsGNNLPZmac4ROagyM4qtbp10EcmUnLJquW6Hzw/O3YSAZEVx+prYR0V5Fts6wkXsyytnZt2jym0S7yzZTEaYqOtrTyLDAlMD9PDrVoOoyCh+HmykkDlwzkicsIxE1W9pppM9RNw3oVVVhtFF3Suy7w4FZJkVKx5BNo1+ng8IOPBVYgA3JEJVB8qRe6VKQHQF+Pu6oU5icrxZ9B7yPZxlji7VMix1EX5vCa4AIUkNWJW/u2SWtSemAKBjBJXar4VsXky4mNbcIwZe4W9QGCgTm9zLfBjuvgAS7OyPpMqHqrt1BFGsx2Kz0K0Vt1zrzQTriQuhEHPbD2tnGsVX38tyq73eLrn4YNW9MBqX683zxcJrtc/wMu6uRY8weZ8QaUKs84m9TGQUIf2bmO7+xMIFf5KZ9Sa3FUbB/t3i9FXO5w7DyrvChvICXNlCqikoUNWVz75hjE9Knu/sHQT92BG8eAhZaZUDOt3WZdfVmGGBfRCNapUWF+2Q+d9M/9tQr2NWO2ByPtG4xgpiDAcSjWn9gq/WB22EcovXNml7oiJntxJIU2/ICQXVMN/hJs6XGXWx/CLhY3AHjgmz0upj9cwRt8Dwy1O0wZusKDuaDAYptU7sE5mnx6YeGPsusyKbtd2YvdvqSklxA+oI= # GH_TOKEN

cache:
  yarn: true
  directories:
    - /home/travis/.rvm/

before_install:
  - rvm install 2.5.1
  - rvm use 2.5.1 --fuzzy
  - export GEMDIR=$(rvm gemdir)
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - yarn install
  - gem install bundler
  - bundle install

script:
  - gulp --env=production build
  - #htmlproofer ./web --allow-hash-href --check-favicon --only-4xx --alt-ignore "/.*/" --url-ignore "/#0/" --log-level=:debug
  - test $TRAVIS_PULL_REQUEST = false && ./deploy.sh

branches:
  only:
    - dev

notifications:
  webhooks:
    secure: QjLOJOPsNZxoVcSI+fn6tWXp7TDb+t2Eykm55TI85ctb0JA8yepQDLfPT0HfnYt/Hnd8bME3No9JPE8H1kDlR+XaaG1fFWIBnQdDWySJKDIndOGb8gKLDUbvFPO/YRoLIsTrItEh//EJgSApkwqVlZbJIJ+if1lPzIsIy9/dG+3gaTc99VR7O0RZuwkkC0t+xgbMjrFpTSmgbMPAOB4jwFqrNKUQBc5Kxjd/wIqM1ZsWtQ4lFHUKQJBgTsnH5o2JMkpkwUJ+XHrWnmknJTD4mVwl1es2axUicumhERiyGN1WrDwY2kVs9UI0AqLHYNeBP3aNXV2lwngkmt59MIFpnqT6ELlOb34WKDCaNTXMzHBphtzevzXshGOUPB6be0S4ai2xukAq1rOzDhUSNzhrupxjjb8FhxHz0TtoKjcAO1ZlT+92dIgcEPx3qf3Y9e46lUKEokidmZOhwHnT0D0uF7LJ+c2z9oopG7DyzBNIVDTyitQmdlvfCUc+RJRfnDQ/8v5qoI8TzkJ6VXwpyWWdZJRJIknkWwf2BKxkGP1pCCSsfSiSKAvsRa1GPq6ztfnfC4jcrfurnSFrLmeGc4+kvDXuYiC4NZ6LoezDsjUKnR3gf1s0IvZNurcb6PA0yPIoAnOWzUYR8ObOcU1gs51zvXsDqxZC3D+O4lChHWsOy8U=
