name: website

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Dump GitHub env
        run: |
          env
      -
        name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      -
        name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 11
      -
        name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          version: 2.6.x
      -
        name: Set up Bundler
        run: |
          gem install bundler -v 2.0.2
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Yarn install
        run: |
          yarn install
      -
        name: Bundle install
        run: |
          bundle install
      -
        name: Build
        env:
          JEKYLL_ENV: production
          JEKYLL_LOG_LEVEL: info
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
        run: |
          gulp --env=production build
          #htmlproofer ./web --allow-hash-href --check-favicon --only-4xx --alt-ignore "/.*/" --url-ignore "/#0/" --log-level=:debug
      -
        name: Deploy
        if: success() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@master
        with:
          target_branch: master
          build_dir: web
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
